### ISSUE TITLE
nodejs npm error

### ISSUE THREAD

**Issue by vimagick** [gliderlabs/docker-alpine#127]
I'm trying run `nodejs` inside alpine docker container.
But `npm` doesn't work. Please help! Thank you!

```
$ docker pull alpine

$ docker run --rm -it alpine sh

>>> cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.3.1
PRETTY_NAME="Alpine Linux v3.3"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

>>> apk add -U nodejs

>>> node --version
v4.2.4

>>> npm --version
2.14.12

>>> npm
Error: error:26078067:engine routines:ENGINE_LIST_ADD:conflicting engine id
    at Error (native)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at getDefaultSessionIdContext (_tls_wrap.js:27:19)
    at _tls_wrap.js:17:33
    at NativeModule.compile (node.js:954:5)
    at NativeModule.require (node.js:902:18)
    at tls.js:221:21
    at NativeModule.compile (node.js:954:5)
    at NativeModule.require (node.js:902:18)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! error:26078067:engine routines:ENGINE_LIST_ADD:conflicting engine id
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
crypto.js:50
  this._handle = new binding.Hash(algorithm);
                 ^

Error: error:2606906E:engine routines:ENGINE_add:internal list error
    at Error (native)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at md5hex (/usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:6:21)
    at getTmpname (/usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:15:27)
    at new WriteStream (/usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:31:22)
    at WriteStream (/usr/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:26:12)
    at writeLogFile (/usr/lib/node_modules/npm/lib/utils/error-handler.js:394:14)
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:80:28)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:385:3)
```

**Comment by ariddell** [comment]
I'm seeing this as well.

**Comment by paulrutter** [comment]
+1, i cannot build my Docker image right now...

**Comment by ariddell** [comment]
http://bugs.alpinelinux.org/issues/4999

**Comment by ariddell** [comment]
One can force alpine to install nodejs from alpine 3.2 with:

``apk-install -X http://alpine.gliderlabs.com/alpine/v3.2/main 'nodejs<0.13'``

**Comment by andyshinn** [comment]
This should be fixed now upstream. Referenced at https://github.com/nodejs/node/issues/4221 and http://git.alpinelinux.org/cgit/aports/commit/?id=30beca0f2f1de59e9fc8632d2807da50057217aa. Thanks @fabled.

**Comment by vimagick** [comment]
:+1:
