### ISSUE TITLE
npm install sqlite3 --build-from-source (fails)

### ISSUE THREAD

**Issue by fractalf** [gliderlabs/docker-alpine#43]
I've had heaps of problems with sqlite3 earlier, but mostly managed to figure it out by reading the errors carefully. This time however I'm quite stuck. Any ideas?

````
FROM alpine:edge

RUN echo "http://nl.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories && \
    echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk add -U iojs wget ca-certificates python make gcc libc-dev g++ && \
    apk upgrade && \
    npm install sqlite3 --build-from-source
````
this will give error
````
...
../src/statement.cc: In static member function 'static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)':
../src/macros.h:122:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:725:5: note: in expansion of macro 'STATEMENT_BEGIN'
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
/usr/lib/gcc/x86_64-alpine-linux-musl/5.1.0/../../../../x86_64-alpine-linux-musl/bin/ld: Release/obj.target/node_sqlite3.node: No symbol version section for versioned symbol `memcpy@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-alpine-linux-musl/5.1.0/../../../../x86_64-alpine-linux-musl/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
node_sqlite3.target.mk:130: recipe for target 'Release/obj.target/node_sqlite3.node' failed
make: *** [Release/obj.target/node_sqlite3.node] Error 1
make: Leaving directory '/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/node_modules/sqlite3/lib/binding/node-v44-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/node_modules/sqlite3/lib/binding/node-v44-linux-x64"
gyp ERR! cwd /node_modules/sqlite3
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
...
````
I suspect it has to do with memcpy@GLIBC_2.2.5, but really I couldn't find out what.

For all I know this might be a io.js issue, but I seem to recall this worked in ubuntu base image

Full log (commands and all errors)
http://pastebin.com/YZShJzY2

Thanks for any input

**Comment by andyshinn** [comment]
It looks like you already have an issue upstream at https://github.com/mapbox/node-sqlite3/issues/459. I'm going to close this one as it needs to be fixed upstream. It looks like you are already installing the required dependencies to build. Ping me in mapbox/node-sqlite3#459 if you need help testing a fix.
