### ISSUE TITLE
openjdk8-jre 8.201.08-r0 breaks kinesis client

### ISSUE THREAD

**Issue by geleman** [gliderlabs/docker-alpine#504]
It looks like the openjdk8-jre version was updated from 8.191.12-r0 on the 15th and this now breaks amazon kinesis client < 2.0.x. Why is this not only in the edge release and backported to prior versions? We have to use 3.9 since that is the only version pulls in libcouchbase 2.9.x. Is there a way to pull the older version in since this is a breaking change? We cannot continue to use this image in this state.

**Comment by amjad1233** [comment]
Subscribing Same issue while installing justb4/jmeter stuff it's not getting `nss` libraries which you have to install in addition.

**Comment by Zethson** [comment]
Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
	at sun.security.pkcs11.Secmod.initialize(Secmod.java:193)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:218)
	... 91 more

Having the same issue. This is a breaking change!

**Comment by Zethson** [comment]
@geleman 
Workaround is proposed here: https://github.com/docker-library/openjdk/issues/289
Make sure, that you remove this as soon as it got fixed!

**Comment by geleman** [comment]
i'm pulling the openjdk image that has the 8.119.12-r0 version specifically at this point. I will continue to check on this to see if it gets resolved

**Comment by esantiagovieira** [comment]
@geleman may you point out how I can do the same? Getting the same issue with my Tomcat image.
For the moment, I was able to fix the issue changing line 85 of the Dockerfile to match the expected java version. The container is running and the service seems to be working as expected, but honestly, I have no real idea of the impact this change is causing.

**Comment by geleman** [comment]
@esantiagovieira I'm using this image  openjdk:8u191-alpine3.9
